/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provaParte02;

import java.awt.Color;

import javax.swing.JOptionPane;

/**
 *
 * @author Fagner
 */
public class Jogooo extends javax.swing.JFrame {

    private Baralho baralho;
    private Jogador jogador01;
    private Jogador jogador02;
    private Jogador jDaVez;
    private CartaBaralho cartaAtualJogadorUm;
    private CartaBaralho cartaAtualJogadorDois;
    private Integer totalJogadas;
    private Integer pontosJogador01;
    private Integer pontosJogador02;
    private Integer numeroDVitoriaJ1 = 0;
    private Integer numeroDVitoriaJ2 = 0;
    private Integer numeroDEmpates = 0;
    private Integer numeroMaior01 = 0;
    private Integer numeroMaior02 = 0;

    /**
     * Creates new form Jogooo
     */

    public Jogooo() {
        initComponents();

        this.baralho = new Baralho();
        this.jogador01 = new Jogador("Carolayne", baralho.puxarMao());
        this.jogador02 = new Jogador("Carol", baralho.puxarMao());
        this.jDaVez = jogador01;

        this.totalJogadas = 0;
        this.pontosJogador01 = 0;
        this.pontosJogador02 = 0;

    }
//// Calcular os pontos e mostrar 
    public void calcularPontos() {
        Integer pontosCartaUm = this.cartaAtualJogadorUm.getCarta().getPontos();
        Integer pontosCartaDois = this.cartaAtualJogadorDois.getCarta().getPontos();;

        if (pontosCartaUm > pontosCartaDois) {
            this.pontosJogador01 += (pontosCartaUm + pontosCartaDois);
            this.numeroDVitoriaJ1 += +1;
            numeroMaior01 = pontosCartaUm;

        } else if (pontosCartaUm < pontosCartaDois) {
            this.pontosJogador02 += (pontosCartaUm + pontosCartaDois);
            numeroMaior02 = pontosCartaDois;
            this.numeroDVitoriaJ2 += +1;
        } else if (pontosCartaUm == pontosCartaDois) {
            this.numeroDEmpates += +1;
        }

        this.textJogado01.setText(this.pontosJogador01.toString());
        this.textJogador02.setText(this.pontosJogador02.toString());
        this.textV1.setText(String.valueOf(numeroDVitoriaJ1));
        this.textV2.setText(String.valueOf(numeroDVitoriaJ2));
        this.textEmpate.setText(String.valueOf(numeroDEmpates));

        if (this.totalJogadas == 10) {
            if (this.pontosJogador01 > this.pontosJogador02) {
                JOptionPane.showMessageDialog(this, " Vencedor  Jogador01 ");

            } else if (this.pontosJogador01 < this.pontosJogador02) {
                JOptionPane.showMessageDialog(this, "Vencedor Jogador02");
            } else {
                JOptionPane.showMessageDialog(this, " A partida deu empate ");
            }
        }
    }

    public void numerosate05() {
        if (numeroMaior01 < numeroMaior02) {
            // jButton10.setBackground(Color.GREEN);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        BJogado01 = new javax.swing.JButton();
        textJogado01 = new javax.swing.JTextField();
        BJogador02 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textJogador02 = new javax.swing.JTextField();
        jButtonJogaNovamente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textV1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textV2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textEmpate = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(1);
        jButton1.setName(""); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.white);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.white);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(java.awt.Color.white);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(java.awt.Color.white);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(java.awt.Color.white);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(java.awt.Color.white);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(java.awt.Color.white);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        BJogado01.setText("Jogador 01");
        BJogado01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJogado01ActionPerformed(evt);
            }
        });

        textJogado01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textJogado01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJogado01ActionPerformed(evt);
            }
        });

        BJogador02.setText("Jogador 02");
        BJogador02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJogador02ActionPerformed(evt);
            }
        });

        jLabel1.setText("                              Placar");

        textJogador02.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonJogaNovamente.setText("Jogar novamente");
        jButtonJogaNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogaNovamenteActionPerformed(evt);
            }
        });

        jLabel2.setText("N vitórias");

        textV1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textV1ActionPerformed(evt);
            }
        });

        jLabel3.setText("N vitórias");

        textV2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textV2ActionPerformed(evt);
            }
        });

        jLabel4.setText("N empates ");

        textEmpate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textEmpate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmpateActionPerformed(evt);
            }
        });

        jButton8.setBackground(java.awt.Color.white);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setPreferredSize(new java.awt.Dimension(70, 180));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BJogado01)
                            .addGap(1, 1, 1)
                            .addComponent(textJogado01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(BJogador02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(textJogador02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButtonJogaNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(textV1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(textV2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(textEmpate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 140, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BJogado01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textJogado01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BJogador02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textJogador02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonJogaNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textEmpate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jButton1.getIcon() == null && jDaVez.equals(jogador01)) {
            jButton1.setIcon(this.jogador01.getMao().get(0).getImagem());
            cartaAtualJogadorUm = this.jogador01.getMao().get(0);
            jDaVez = jogador02;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jButton2.getIcon() == null && jDaVez.equals(jogador01)) {
            jButton2.setIcon(this.jogador01.getMao().get(1).getImagem());
            cartaAtualJogadorUm = this.jogador01.getMao().get(1);
            jDaVez = jogador02;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jButton3.getIcon() == null && jDaVez.equals(jogador01)) {
            jButton3.setIcon(this.jogador01.getMao().get(2).getImagem());
            cartaAtualJogadorUm = this.jogador01.getMao().get(2);
            jDaVez = jogador02;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jButton4.getIcon() == null && jDaVez.equals(jogador01)) {
            jButton4.setIcon(this.jogador01.getMao().get(3).getImagem());
            cartaAtualJogadorUm = this.jogador01.getMao().get(3);
            jDaVez = jogador02;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jButton5.getIcon() == null && jDaVez.equals(jogador01)) {
            jButton5.setIcon(this.jogador01.getMao().get(4).getImagem());
            cartaAtualJogadorUm = this.jogador01.getMao().get(4);
            jDaVez = jogador02;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jButton6.getIcon() == null && jDaVez.equals(jogador02)) {
            jButton6.setIcon(this.jogador02.getMao().get(4).getImagem());
            cartaAtualJogadorDois = this.jogador02.getMao().get(0);
            jDaVez = jogador01;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();

            }

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jButton7.getIcon() == null && jDaVez.equals(jogador02)) {
            jButton7.setIcon(this.jogador02.getMao().get(1).getImagem());
            cartaAtualJogadorDois = this.jogador02.getMao().get(1);
            jDaVez = jogador01;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (jButton9.getIcon() == null && jDaVez.equals(jogador02)) {
            jButton9.setIcon(this.jogador02.getMao().get(3).getImagem());
            cartaAtualJogadorDois = this.jogador02.getMao().get(3);
            jDaVez = jogador01;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (jButton10.getIcon() == null && jDaVez.equals(jogador02)) {
            jButton10.setIcon(this.jogador02.getMao().get(4).getImagem());
            cartaAtualJogadorDois = this.jogador02.getMao().get(4);
            jDaVez = jogador01;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void textJogado01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJogado01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJogado01ActionPerformed

    private void jButtonJogaNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogaNovamenteActionPerformed
        this.baralho = new Baralho();
        this.jogador01 = new Jogador("Carolayne", baralho.puxarMao());
        this.jogador02 = new Jogador("Carol", baralho.puxarMao());
        this.jDaVez = jogador01;
        this.totalJogadas = 0;
        this.pontosJogador01 = 0;
        this.pontosJogador02 = 0;

        this.textJogado01.setText("0");
        this.textJogador02.setText("0");
        this.textEmpate.setText("0");
        this.textV1.setText("0");
        this.textV2.setText("0");
        this.jButton1.setIcon(null);
        this.jButton2.setIcon(null);
        this.jButton3.setIcon(null);
        this.jButton4.setIcon(null);
        this.jButton5.setIcon(null);
        this.jButton6.setIcon(null);
        this.jButton7.setIcon(null);
        this.jButton8.setIcon(null);
        this.jButton9.setIcon(null);
        this.jButton10.setIcon(null);
    }//GEN-LAST:event_jButtonJogaNovamenteActionPerformed

    private void textV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textV1ActionPerformed

    private void textV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textV2ActionPerformed

    private void textEmpateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmpateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmpateActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jButton8.getIcon() == null && jDaVez.equals(jogador02)) {
            jButton8.setIcon(this.jogador02.getMao().get(2).getImagem());
            cartaAtualJogadorDois = this.jogador02.getMao().get(2);
            jDaVez = jogador01;
            this.totalJogadas++;
            if (totalJogadas % 2 == 0) {
                calcularPontos();
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void BJogador02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJogador02ActionPerformed

    }//GEN-LAST:event_BJogador02ActionPerformed

    private void BJogado01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJogado01ActionPerformed

    }//GEN-LAST:event_BJogado01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogooo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BJogado01;
    private javax.swing.JButton BJogador02;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonJogaNovamente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textEmpate;
    private javax.swing.JTextField textJogado01;
    private javax.swing.JTextField textJogador02;
    private javax.swing.JTextField textV1;
    private javax.swing.JTextField textV2;
    // End of variables declaration//GEN-END:variables
}
